/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#b02f00",
        "primary-container": "#ff5722",
        "on-primary": "#ffffff",
        "on-primary-container": "#541200",
        "on-primary-fixed": "#3b0900",
        "on-primary-fixed-variant": "#862200",
        "primary-fixed": "#ffdbd1",
        "primary-fixed-dim": "#ffb5a0",
        "inverse-primary": "#ffb5a0",

        "secondary": "#0058be",
        "secondary-container": "#2170e4",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#004395",

        "tertiary": "#735c00",
        "tertiary-container": "#cea700",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4e3d00",
        "tertiary-fixed": "#ffe083",
        "tertiary-fixed-dim": "#eec200",
        "on-tertiary-fixed": "#231b00",
        "on-tertiary-fixed-variant": "#574500",

        "background": "#faf8ff",
        "on-background": "#131b2e",

        "surface": "#faf8ff",
        "on-surface": "#131b2e",
        "surface-variant": "#dae2fd",
        "on-surface-variant": "#5b4039",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container": "#eaedff",
        "surface-container-low": "#f2f3ff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#b02f00",

        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        "outline": "#907067",
        "outline-variant": "#e4beb4",

        // Legacy compatibility tokens
        "brand-cream": "#FFF8EC",
        "hub-cream": "#FFF7E8",
        "hub-navy": "#243447",
        "hub-blue": "#2563EB",
        "hub-yellow": "#FBBF24",
        "hub-green": "#D1E8E2",
      },
      borderRadius: {
        "custom": "20px",
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "margin": "2rem",
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "section-gap-lg": "120px",
        "section-gap-md": "80px",
        "container-max": "1280px",
        "base": "8px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Space Grotesk", "sans-serif"],
        "label-lg": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "display-md": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "display-md-mobile": ["Space Grotesk", "sans-serif"],
        "display-lg-mobile": ["Space Grotesk", "sans-serif"],
        "space-grotesk": ["Space Grotesk", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        "poppins": ["Poppins", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-md": ["40px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["56px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-md-mobile": ["28px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
