services:
  - type: web
    name: student-resource-hub-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node src/server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLIENT_ORIGIN
        value: https://campus-hub-eight-omega.vercel.app
      - key: ALLOWED_ORIGIN
        value: https://campus-hub-eight-omega.vercel.app
      - key: COOKIE_SECURE
        value: "true"
      - key: COOKIE_SAME_SITE
        value: none
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
